# This file was generated by GoReleaser. DO NOT EDIT.
cask "logo-ls" do
  version "1.7.0"

  on_macos do
    on_intel do
      sha256 "bdf0007bc800c143af1edcae1879887891f0daf7133521900fd7a54911b58f06"
      url "https://github.com/canta2899/logo-ls/releases/download/v#{version}/logo-ls-v#{version}-darwin-amd64.tar.gz",
        verified: "github.com/canta2899/logo-ls/"
    end
    on_arm do
      sha256 "54ec015531fbfbd6055bc057abe87b7871bdda31247cee716a4962cd49f7d277"
      url "https://github.com/canta2899/logo-ls/releases/download/v#{version}/logo-ls-v#{version}-darwin-arm64.tar.gz",
        verified: "github.com/canta2899/logo-ls/"
    end
  end

  on_linux do
    on_intel do
      sha256 "a34c4b39d01da779f0285f0ca44fbae7ee13cd1d909a265f22864c68e6435f05"
      url "https://github.com/canta2899/logo-ls/releases/download/v#{version}/logo-ls-v#{version}-linux-amd64.tar.gz",
        verified: "github.com/canta2899/logo-ls/"
    end
    on_arm do
      sha256 "5702c75b6a86ed46a30e4f039cacb1e288225b7d33feaeab21b11e9dd67494a2"
      url "https://github.com/canta2899/logo-ls/releases/download/v#{version}/logo-ls-v#{version}-linux-arm64.tar.gz",
        verified: "github.com/canta2899/logo-ls/"
    end
  end

  name "logo-ls"
  desc "A minimal ls replacement, with git status indicators and configurable Nerd Font icons"
  homepage "https://github.com/canta2899/logo-ls"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "logo-ls"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/logo-ls"]
    end
  end

  # No zap stanza required

end
