# This file was generated by GoReleaser. DO NOT EDIT.
cask "logo-ls" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "logo-ls"], chdir: "."
    end
  end

  version "1.7.4"

  on_macos do
    on_arm do
      sha256 "4585a6665638d28edb5606f652665914ebdfadd9ab571dcf2239b0a09cf3a573"
      url "https://github.com/canta2899/logo-ls/releases/download/v#{version}/logo-ls-v#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "0eb12e7d47baa7ad61d0b16958ba23b87c5f6033d17239faf3fd8a77216404c9"
      url "https://github.com/canta2899/logo-ls/releases/download/v#{version}/logo-ls-v#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "77fa4f03cb4348caec936435d868ac985185ca163dc018f0000e99d4f11644d1"
      url "https://github.com/canta2899/logo-ls/releases/download/v#{version}/logo-ls-v#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "e73610780b729350a541406445de93a99bb78883db161414919d6d76be4a8939"
      url "https://github.com/canta2899/logo-ls/releases/download/v#{version}/logo-ls-v#{version}-linux-amd64.tar.gz"
    end
  end

  name "logo-ls"
  desc "A minimal ls replacement, with git status indicators and configurable Nerd Font icons"
  homepage "https://github.com/canta2899/logo-ls"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "logo-ls"

  # No zap stanza required
end
