# This file was generated by GoReleaser. DO NOT EDIT.
cask "logo-ls" do
  version "1.7.2"

  on_macos do
    on_arm do
      sha256 "d8181944f4163d8c891a3cdff00dd2d738f06b3baed4ddb1096df6b58b0aa113"
      url "https://github.com/canta2899/logo-ls/releases/download/v#{version}/logo-ls-v#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "cc6dc3fac43dabef9d17984ab731fcb401b41ae8d21a8eaa411217f748538ef6"
      url "https://github.com/canta2899/logo-ls/releases/download/v#{version}/logo-ls-v#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9ca549d4add418097a3a00a12e5f5007f251000f4aa6e8559754cb2b641543c4"
      url "https://github.com/canta2899/logo-ls/releases/download/v#{version}/logo-ls-v#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "346038f0121a3600583c2c84b5795f70b6f67834156d41ef12f7d6e34d47fd69"
      url "https://github.com/canta2899/logo-ls/releases/download/v#{version}/logo-ls-v#{version}-linux-amd64.tar.gz"
    end
  end

  name "logo-ls"
  desc "A minimal ls replacement, with git status indicators and configurable Nerd Font icons"
  homepage "https://github.com/canta2899/logo-ls"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "logo-ls"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/logo-ls"]
    end
  end

  # No zap stanza required
end
